require("oil").setup({
	delete_to_trash = true,
	skip_confirm_for_simple_edits = true,
	experimental_watch_for_changes = true,
	keymaps = {
		["g?"] = "actions.show_help",
		["<CR>"] = "actions.select",
		["<C-w>j"] = "actions.select_split",
		["<C-w><C-j>"] = "actions.select_split",
		["<C-w>k"] = "actions.select_vsplit",
		["<C-w><C-k>"] = "actions.select_vsplit",
		["<C-t>"] = "actions.select_tab",
		["<C-p>"] = "actions.preview",
		["<C-c>"] = "actions.close",
		["<esc><esc>"] = "actions.close",
		["<leader>l"] = "actions.refresh",
		["<M-p>"] = "actions.preview_scroll_up",
		["<M-n>"] = "actions.preview_scroll_down",
		["-"] = "actions.parent",
		["_"] = "actions.open_cwd",
		["`"] = "actions.cd",
		["~"] = "actions.tcd",
		["gs"] = "actions.change_sort",
		["gx"] = "actions.open_external",
		["g."] = "actions.toggle_hidden",
		["g/"] = "actions.toggle_trash",
	},
	keymaps_help = {
		border = "rounded",
	},
	use_default_keymaps = false,
})
